# local, dev, prod 공통 설정
server:
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.knpharm.pm.dto
  mapper-locations: mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

# Thymleaf
spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML

---
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      location: "C:\\upload"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knpharm?serverTimezone=Asia/Seoul
    username: root
    password: master
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false # 개발시에는 수정시 즉시 반영 가능하게.
server:
  port: 80

---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      location: "/data/upload/dev"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pm.coregen.co.kr:3306/kntest?serverTimezone=Asia/Seoul
    username: kndev
    password: dev@w2w
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false # 개발시에는 수정시 즉시 반영 가능하게.
server:
  port: 8072

---
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      location: "/data/upload/prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knpharm?serverTimezone=Asia/Seoul
    username: pm
    password: kn@w2w
  thymeleaf:
    cache: true
server:
  port: 8082